### ISSUE TITLE
换图片后，对应面显示为黑

### ISSUE THREAD

**Issue by KangHarrison** [lbb00/3d-blind-box#1]
替换frontImg中链接后，前后两面直接黑了。
<img width="380" alt="image" src="https://user-images.githubusercontent.com/38460769/233437325-ab54aa76-d7a5-4fed-8137-0c9da170b212.png">

**Comment by lbb00** [comment]
是不是你的图片有点问题，多换几张图试试

**Comment by KangHarrison** [comment]
> 是不是你的图片有点问题，多换几张图试试

是的，我换成其他的图床的就好了
